import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading } = api.post.getAll.useQuery();

  const { mutate } = api.post.create.useMutation({
    onSuccess: () => console.log("1111"),
    onError: (e) => console.log(e),
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="text-white">
          <p className="text-2xl text-white">
            {!isLoading ? JSON.stringify(data) : "Loading tRPC query..."}
          </p>
          <button
            onClick={() =>
              mutate({
                name: "test",
              })
            }
          >
            create post
          </button>
        </div>
      </main>
    </>
  );
}
